-- TurkishMMLU içe aktarımı için PLACEHOLDER kazanım satırları.
-- Bunlar ince taneli kazanım (örn. MAT.9.2.1) DEĞİLDIR — sadece ders+sınıf
-- düzeyinde kaba bir gruplamadır. İçerik Uzmanı, ilişkili sorulara gerçek
-- kazanım kodu atadıkça bu placeholder'lar terk edilebilir.

INSERT INTO learning_outcomes (code, description, subject, grade_level) VALUES ('BIY.10.GENEL', 'Biyoloji 10. Sınıf — Genel (TurkishMMLU içe aktarım placeholder''ı; gerçek kazanım ataması İçerik Uzmanı tarafından yapılmalıdır)', 'Biyoloji', 10);
INSERT INTO learning_outcomes (code, description, subject, grade_level) VALUES ('COG.10.GENEL', 'Coğrafya 10. Sınıf — Genel (TurkishMMLU içe aktarım placeholder''ı; gerçek kazanım ataması İçerik Uzmanı tarafından yapılmalıdır)', 'Coğrafya', 10);
INSERT INTO learning_outcomes (code, description, subject, grade_level) VALUES ('DKAB.10.GENEL', 'Din Kültürü ve Ahlak Bilgisi 10. Sınıf — Genel (TurkishMMLU içe aktarım placeholder''ı; gerçek kazanım ataması İçerik Uzmanı tarafından yapılmalıdır)', 'Din Kültürü ve Ahlak Bilgisi', 10);
INSERT INTO learning_outcomes (code, description, subject, grade_level) VALUES ('FEL.10.GENEL', 'Felsefe 10. Sınıf — Genel (TurkishMMLU içe aktarım placeholder''ı; gerçek kazanım ataması İçerik Uzmanı tarafından yapılmalıdır)', 'Felsefe', 10);
INSERT INTO learning_outcomes (code, description, subject, grade_level) VALUES ('FIZ.10.GENEL', 'Fizik 10. Sınıf — Genel (TurkishMMLU içe aktarım placeholder''ı; gerçek kazanım ataması İçerik Uzmanı tarafından yapılmalıdır)', 'Fizik', 10);
INSERT INTO learning_outcomes (code, description, subject, grade_level) VALUES ('KIM.10.GENEL', 'Kimya 10. Sınıf — Genel (TurkishMMLU içe aktarım placeholder''ı; gerçek kazanım ataması İçerik Uzmanı tarafından yapılmalıdır)', 'Kimya', 10);
INSERT INTO learning_outcomes (code, description, subject, grade_level) VALUES ('MAT.10.GENEL', 'Matematik 10. Sınıf — Genel (TurkishMMLU içe aktarım placeholder''ı; gerçek kazanım ataması İçerik Uzmanı tarafından yapılmalıdır)', 'Matematik', 10);
INSERT INTO learning_outcomes (code, description, subject, grade_level) VALUES ('TAR.10.GENEL', 'Tarih 10. Sınıf — Genel (TurkishMMLU içe aktarım placeholder''ı; gerçek kazanım ataması İçerik Uzmanı tarafından yapılmalıdır)', 'Tarih', 10);
INSERT INTO learning_outcomes (code, description, subject, grade_level) VALUES ('TDE.10.GENEL', 'Türk Dili ve Edebiyatı 10. Sınıf — Genel (TurkishMMLU içe aktarım placeholder''ı; gerçek kazanım ataması İçerik Uzmanı tarafından yapılmalıdır)', 'Türk Dili ve Edebiyatı', 10);
INSERT INTO learning_outcomes (code, description, subject, grade_level) VALUES ('BIY.11.GENEL', 'Biyoloji 11. Sınıf — Genel (TurkishMMLU içe aktarım placeholder''ı; gerçek kazanım ataması İçerik Uzmanı tarafından yapılmalıdır)', 'Biyoloji', 11);
INSERT INTO learning_outcomes (code, description, subject, grade_level) VALUES ('COG.11.GENEL', 'Coğrafya 11. Sınıf — Genel (TurkishMMLU içe aktarım placeholder''ı; gerçek kazanım ataması İçerik Uzmanı tarafından yapılmalıdır)', 'Coğrafya', 11);
INSERT INTO learning_outcomes (code, description, subject, grade_level) VALUES ('DKAB.11.GENEL', 'Din Kültürü ve Ahlak Bilgisi 11. Sınıf — Genel (TurkishMMLU içe aktarım placeholder''ı; gerçek kazanım ataması İçerik Uzmanı tarafından yapılmalıdır)', 'Din Kültürü ve Ahlak Bilgisi', 11);
INSERT INTO learning_outcomes (code, description, subject, grade_level) VALUES ('FEL.11.GENEL', 'Felsefe 11. Sınıf — Genel (TurkishMMLU içe aktarım placeholder''ı; gerçek kazanım ataması İçerik Uzmanı tarafından yapılmalıdır)', 'Felsefe', 11);
INSERT INTO learning_outcomes (code, description, subject, grade_level) VALUES ('FIZ.11.GENEL', 'Fizik 11. Sınıf — Genel (TurkishMMLU içe aktarım placeholder''ı; gerçek kazanım ataması İçerik Uzmanı tarafından yapılmalıdır)', 'Fizik', 11);
INSERT INTO learning_outcomes (code, description, subject, grade_level) VALUES ('KIM.11.GENEL', 'Kimya 11. Sınıf — Genel (TurkishMMLU içe aktarım placeholder''ı; gerçek kazanım ataması İçerik Uzmanı tarafından yapılmalıdır)', 'Kimya', 11);
INSERT INTO learning_outcomes (code, description, subject, grade_level) VALUES ('MAT.11.GENEL', 'Matematik 11. Sınıf — Genel (TurkishMMLU içe aktarım placeholder''ı; gerçek kazanım ataması İçerik Uzmanı tarafından yapılmalıdır)', 'Matematik', 11);
INSERT INTO learning_outcomes (code, description, subject, grade_level) VALUES ('TAR.11.GENEL', 'Tarih 11. Sınıf — Genel (TurkishMMLU içe aktarım placeholder''ı; gerçek kazanım ataması İçerik Uzmanı tarafından yapılmalıdır)', 'Tarih', 11);
INSERT INTO learning_outcomes (code, description, subject, grade_level) VALUES ('TDE.11.GENEL', 'Türk Dili ve Edebiyatı 11. Sınıf — Genel (TurkishMMLU içe aktarım placeholder''ı; gerçek kazanım ataması İçerik Uzmanı tarafından yapılmalıdır)', 'Türk Dili ve Edebiyatı', 11);
INSERT INTO learning_outcomes (code, description, subject, grade_level) VALUES ('BIY.12.GENEL', 'Biyoloji 12. Sınıf — Genel (TurkishMMLU içe aktarım placeholder''ı; gerçek kazanım ataması İçerik Uzmanı tarafından yapılmalıdır)', 'Biyoloji', 12);
INSERT INTO learning_outcomes (code, description, subject, grade_level) VALUES ('COG.12.GENEL', 'Coğrafya 12. Sınıf — Genel (TurkishMMLU içe aktarım placeholder''ı; gerçek kazanım ataması İçerik Uzmanı tarafından yapılmalıdır)', 'Coğrafya', 12);
INSERT INTO learning_outcomes (code, description, subject, grade_level) VALUES ('DKAB.12.GENEL', 'Din Kültürü ve Ahlak Bilgisi 12. Sınıf — Genel (TurkishMMLU içe aktarım placeholder''ı; gerçek kazanım ataması İçerik Uzmanı tarafından yapılmalıdır)', 'Din Kültürü ve Ahlak Bilgisi', 12);
INSERT INTO learning_outcomes (code, description, subject, grade_level) VALUES ('FIZ.12.GENEL', 'Fizik 12. Sınıf — Genel (TurkishMMLU içe aktarım placeholder''ı; gerçek kazanım ataması İçerik Uzmanı tarafından yapılmalıdır)', 'Fizik', 12);
INSERT INTO learning_outcomes (code, description, subject, grade_level) VALUES ('KIM.12.GENEL', 'Kimya 12. Sınıf — Genel (TurkishMMLU içe aktarım placeholder''ı; gerçek kazanım ataması İçerik Uzmanı tarafından yapılmalıdır)', 'Kimya', 12);
INSERT INTO learning_outcomes (code, description, subject, grade_level) VALUES ('MAT.12.GENEL', 'Matematik 12. Sınıf — Genel (TurkishMMLU içe aktarım placeholder''ı; gerçek kazanım ataması İçerik Uzmanı tarafından yapılmalıdır)', 'Matematik', 12);
INSERT INTO learning_outcomes (code, description, subject, grade_level) VALUES ('TAR.12.GENEL', 'Tarih 12. Sınıf — Genel (TurkishMMLU içe aktarım placeholder''ı; gerçek kazanım ataması İçerik Uzmanı tarafından yapılmalıdır)', 'Tarih', 12);
INSERT INTO learning_outcomes (code, description, subject, grade_level) VALUES ('TDE.12.GENEL', 'Türk Dili ve Edebiyatı 12. Sınıf — Genel (TurkishMMLU içe aktarım placeholder''ı; gerçek kazanım ataması İçerik Uzmanı tarafından yapılmalıdır)', 'Türk Dili ve Edebiyatı', 12);
INSERT INTO learning_outcomes (code, description, subject, grade_level) VALUES ('BIY.9.GENEL', 'Biyoloji 9. Sınıf — Genel (TurkishMMLU içe aktarım placeholder''ı; gerçek kazanım ataması İçerik Uzmanı tarafından yapılmalıdır)', 'Biyoloji', 9);
INSERT INTO learning_outcomes (code, description, subject, grade_level) VALUES ('COG.9.GENEL', 'Coğrafya 9. Sınıf — Genel (TurkishMMLU içe aktarım placeholder''ı; gerçek kazanım ataması İçerik Uzmanı tarafından yapılmalıdır)', 'Coğrafya', 9);
INSERT INTO learning_outcomes (code, description, subject, grade_level) VALUES ('DKAB.9.GENEL', 'Din Kültürü ve Ahlak Bilgisi 9. Sınıf — Genel (TurkishMMLU içe aktarım placeholder''ı; gerçek kazanım ataması İçerik Uzmanı tarafından yapılmalıdır)', 'Din Kültürü ve Ahlak Bilgisi', 9);
INSERT INTO learning_outcomes (code, description, subject, grade_level) VALUES ('FIZ.9.GENEL', 'Fizik 9. Sınıf — Genel (TurkishMMLU içe aktarım placeholder''ı; gerçek kazanım ataması İçerik Uzmanı tarafından yapılmalıdır)', 'Fizik', 9);
INSERT INTO learning_outcomes (code, description, subject, grade_level) VALUES ('KIM.9.GENEL', 'Kimya 9. Sınıf — Genel (TurkishMMLU içe aktarım placeholder''ı; gerçek kazanım ataması İçerik Uzmanı tarafından yapılmalıdır)', 'Kimya', 9);
INSERT INTO learning_outcomes (code, description, subject, grade_level) VALUES ('MAT.9.GENEL', 'Matematik 9. Sınıf — Genel (TurkishMMLU içe aktarım placeholder''ı; gerçek kazanım ataması İçerik Uzmanı tarafından yapılmalıdır)', 'Matematik', 9);
INSERT INTO learning_outcomes (code, description, subject, grade_level) VALUES ('TAR.9.GENEL', 'Tarih 9. Sınıf — Genel (TurkishMMLU içe aktarım placeholder''ı; gerçek kazanım ataması İçerik Uzmanı tarafından yapılmalıdır)', 'Tarih', 9);
INSERT INTO learning_outcomes (code, description, subject, grade_level) VALUES ('TDE.9.GENEL', 'Türk Dili ve Edebiyatı 9. Sınıf — Genel (TurkishMMLU içe aktarım placeholder''ı; gerçek kazanım ataması İçerik Uzmanı tarafından yapılmalıdır)', 'Türk Dili ve Edebiyatı', 9);
